"""empty message

Revision ID: 542da5faf8f7
Revises: 12041c3018b3
Create Date: 2024-01-28 15:01:55.174005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542da5faf8f7'
down_revision = '12041c3018b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profileImg', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profileImg')

    # ### end Alembic commands ###
