"""empty message

Revision ID: 6421c9c537ae
Revises: 297ab47b6fd5
Create Date: 2024-01-19 16:11:56.242272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6421c9c537ae'
down_revision = '297ab47b6fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inProccess')
    op.drop_table('finished')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finished',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=70), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='finished_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='finished_pkey')
    )
    op.create_table('inProccess',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"inProccess_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=70), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='inProccess_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='inProccess_pkey')
    )
    # ### end Alembic commands ###
